// оновлено 09.09.25: 20:26:36.  Категория цены: БЕЗ ЦЕН //
export const products = {
	"Olija" : {
		"1" :  { 
			"category" : "Олія",
			"productCode" : "2369",
			"productFullName" : "Олія ТМ\"Бокарєв\" 3л. нерафінована",
			"productName" : "Олія Бокарев н\/р 3л.",
			"unit" : "шт.",
			"baseUnit" : "шт.",
			"coefficient" : "1",
			"previousPrice" : "",
			"price" : "",
			"minCountUnit" : "4",
			"promotion" : "1",
			"imgSrc" : "https:\/\/olegeduc.github.io\/food-trade\/image\/2369-olija-tm-bokarjev-3l-nerafinovana.jpg",
			},
		"2" :  { 
			"category" : "Олія",
			"productCode" : "1818",
			"productFullName" : "Олія \"Бокарєв\" нерафінована 5л",
			"productName" : "Олія Бокарев н\/р 5 л",
			"unit" : "шт.",
			"baseUnit" : "шт.",
			"coefficient" : "1",
			"previousPrice" : "",
			"price" : "",
			"minCountUnit" : "2",
			"promotion" : "1",
			"imgSrc" : "https:\/\/olegeduc.github.io\/food-trade\/image\/olija-bokarev-neraf-5-l.jpg",
			},
		"3" :  { 
			"category" : "Олія",
			"productCode" : "3224",
			"productFullName" : "Олія \"Гурман\" нерафінована 2л.",
			"productName" : "Олія Гурман н\/р  2л.",
			"unit" : "шт.",
			"baseUnit" : "шт.",
			"coefficient" : "1",
			"previousPrice" : "",
			"price" : "",
			"minCountUnit" : "6",
			"promotion" : "1",
			"imgSrc" : "https:\/\/olegeduc.github.io\/food-trade\/image\/olija-gurman-neraf-2l.jpg",
			},
		"4" :  { 
			"category" : "Олія",
			"productCode" : "723",
			"productFullName" : "Олія \"Бокарєв\" рафінована 700г.",
			"productName" : "Олія раф  Бокарев 700г.",
			"unit" : "шт.",
			"baseUnit" : "шт.",
			"coefficient" : "1",
			"previousPrice" : "",
			"price" : "",
			"minCountUnit" : "9",
			"promotion" : "1",
			"imgSrc" : "https:\/\/olegeduc.github.io\/food-trade\/image\/olija-bokarev-raf-760-ml.jpg",
			},
		"5" :  { 
			"category" : "Олія",
			"productCode" : "1782",
			"productFullName" : "Олія \"Бокарєв\" рафінована 1л.",
			"productName" : "Олія раф Бокарев 1л.",
			"unit" : "шт.",
			"baseUnit" : "шт.",
			"coefficient" : "1",
			"previousPrice" : "",
			"price" : "",
			"minCountUnit" : "9",
			"promotion" : "1",
			"imgSrc" : "https:\/\/olegeduc.github.io\/food-trade\/image\/1782-olija-bokarjev-rafinovana-1l.jpg",
			},
		"6" :  { 
			"category" : "Олія",
			"productCode" : "729",
			"productFullName" : "Олія ТМ\"Бокарєв\" 3л. рафінована",
			"productName" : "Олія раф Бокарев 3 л.",
			"unit" : "шт.",
			"baseUnit" : "шт.",
			"coefficient" : "1",
			"previousPrice" : "",
			"price" : "",
			"minCountUnit" : "4",
			"promotion" : "1",
			"imgSrc" : "https:\/\/olegeduc.github.io\/food-trade\/image\/729-olija-tm-bokarjev-3l-rafinovana.jpg",
			},
		"7" :  { 
			"category" : "Олія",
			"productCode" : "1819",
			"productFullName" : "Олія \"Бокарєв\" рафінована 5л.",
			"productName" : "Олія раф Бокарев 5л.",
			"unit" : "шт.",
			"baseUnit" : "шт.",
			"coefficient" : "1",
			"previousPrice" : "",
			"price" : "",
			"minCountUnit" : "2",
			"promotion" : "1",
			"imgSrc" : "https:\/\/olegeduc.github.io\/food-trade\/image\/olyja-bokarev-raf-5l.jpg",
			},
		"8" :  { 
			"category" : "Олія",
			"productCode" : "3223",
			"productFullName" : "Олія рафінована \"Гурман\" 2л.",
			"productName" : "Олія раф Гурман 2л.",
			"unit" : "шт.",
			"baseUnit" : "шт.",
			"coefficient" : "1",
			"previousPrice" : "",
			"price" : "",
			"minCountUnit" : "6",
			"promotion" : "1",
			"imgSrc" : "https:\/\/olegeduc.github.io\/food-trade\/image\/3223-olija-gurman-rafinovana-2l.jpg",
			},
		"9" :  { 
			"category" : "Олія",
			"productCode" : "4260",
			"productFullName" : "Олія рафінована ТМ\"Олівія\" 5л.",
			"productName" : "Олія раф Олівія 5л.",
			"unit" : "шт.",
			"baseUnit" : "шт.",
			"coefficient" : "1",
			"previousPrice" : "",
			"price" : "",
			"minCountUnit" : "3",
			"promotion" : "1",
			"imgSrc" : "https:\/\/olegeduc.github.io\/food-trade\/image\/4260-olija-rafinovana-tm-olivija-5-2l.jpg",
			},
	},
}



export const productCategorys = {
	"Olija" : "Олія",
 }

export const anouns = []