// оновлено 09.09.25: 18:54:09.  Категория цены: БЕЗ ЦЕН //
export const products = {
	"Konservi-m'jasni" : {
		"1" :  { 
			"category" : "Консерви м'ясні",
			"productCode" : "1888",
			"productFullName" : "Каша Classo М'ясо гречана з м'ясом 325г.",
			"productName" : "Каша Classo М'ясо Гречана з м'ясом 325 гр",
			"unit" : "шт.",
			"baseUnit" : "шт.",
			"coefficient" : "1",
			"previousPrice" : "",
			"price" : "",
			"minCountUnit" : "5",
			"promotion" : "1",
			"imgSrc" : "https:\/\/olegeduc.github.io\/food-trade\/image\/classo-konservi\\classo-kasha-grechana-z-mjasom-325g.jpg",
			},
		"2" :  { 
			"category" : "Консерви м'ясні",
			"productCode" : "2004",
			"productFullName" : "Каша Classo М'ясо гречана з м'ясом 525г.",
			"productName" : "Каша Classo М'ясо Гречана з м'ясом 525 г",
			"unit" : "шт.",
			"baseUnit" : "шт.",
			"coefficient" : "1",
			"previousPrice" : "",
			"price" : "",
			"minCountUnit" : "5",
			"promotion" : "1",
			"imgSrc" : "https:\/\/olegeduc.github.io\/food-trade\/image\/classo-konservi\\classo-kasha-grechana-z-mjasom-525g.jpg",
			},
		"3" :  { 
			"category" : "Консерви м'ясні",
			"productCode" : "1882",
			"productFullName" : "Паштет Classo М'ясо м'ясний Домашній 300 гр",
			"productName" : "Паштет Classo М'ясо м'ясний Домашній 300 гр",
			"unit" : "шт.",
			"baseUnit" : "шт.",
			"coefficient" : "1",
			"previousPrice" : "",
			"price" : "",
			"minCountUnit" : "18",
			"promotion" : "1",
			"imgSrc" : "https:\/\/olegeduc.github.io\/food-trade\/image\/classo-konservi\\classo-pashtet-mjasnij-domashnij-325g.jpg",
			},
		"4" :  { 
			"category" : "Консерви м'ясні",
			"productCode" : "1890",
			"productFullName" : "Паштет Classo М'ясо печінковий Ніжний 300 гр",
			"productName" : "Паштет Classo М'ясо печінковий Ніжний 300 гр",
			"unit" : "шт.",
			"baseUnit" : "шт.",
			"coefficient" : "1",
			"previousPrice" : "",
			"price" : "",
			"minCountUnit" : "18",
			"promotion" : "1",
			"imgSrc" : "https:\/\/olegeduc.github.io\/food-trade\/image\/classo-konservi\\classo-pashtet-pechinkovij-325g.jpg",
			},
		"5" :  { 
			"category" : "Консерви м'ясні",
			"productCode" : "1887",
			"productFullName" : "Тушонка Classo М'ясо Курка без кістки Елітна 525 гр",
			"productName" : "Тушонка Classo М'ясо Курка без кістки Елітна 525 гр",
			"unit" : "шт.",
			"baseUnit" : "шт.",
			"coefficient" : "1",
			"previousPrice" : "",
			"price" : "",
			"minCountUnit" : "12",
			"promotion" : "1",
			"imgSrc" : "https:\/\/olegeduc.github.io\/food-trade\/image\/classo-konservi\\classo-kurka-elitn-525g.jpg",
			},
		"6" :  { 
			"category" : "Консерви м'ясні",
			"productCode" : "1924",
			"productFullName" : "Тушонка Classo М'ясо Свинина до сніданку 525 гр",
			"productName" : "Тушонка Classo М'ясо Свинина до сніданку 525 гр",
			"unit" : "шт.",
			"baseUnit" : "шт.",
			"coefficient" : "1",
			"previousPrice" : "",
			"price" : "",
			"minCountUnit" : "12",
			"promotion" : "1",
			"imgSrc" : "https:\/\/olegeduc.github.io\/food-trade\/image\/classo-konservi\\classo-svinina-do-snidanku-525g.jpg",
			},
		"7" :  { 
			"category" : "Консерви м'ясні",
			"productCode" : "1879",
			"productFullName" : "Тушонка Classo М'ясо Яловичина класична 325 гр",
			"productName" : "Тушонка Classo М'ясо Яловичина класична 325 гр",
			"unit" : "шт.",
			"baseUnit" : "шт.",
			"coefficient" : "1",
			"previousPrice" : "",
			"price" : "",
			"minCountUnit" : "18",
			"promotion" : "1",
			"imgSrc" : "https:\/\/olegeduc.github.io\/food-trade\/image\/classo-konservi\\classo-jalovichina-klasichna-325g.jpg",
			},
		"8" :  { 
			"category" : "Консерви м'ясні",
			"productCode" : "1878",
			"productFullName" : "Тушонка Classo М'ясо Яловичина класична 525 гр.",
			"productName" : "Тушонка Classo М'ясо Яловичина класична 525 гр.",
			"unit" : "шт.",
			"baseUnit" : "шт.",
			"coefficient" : "1",
			"previousPrice" : "",
			"price" : "",
			"minCountUnit" : "12",
			"promotion" : "1",
			"imgSrc" : "https:\/\/olegeduc.github.io\/food-trade\/image\/classo-konservi\\classo-jalovichina-klasichna-525g.jpg",
			},
		"9" :  { 
			"category" : "Консерви м'ясні",
			"productCode" : "2003",
			"productFullName" : "Тушонка Classo М'ясо Яловичина ніжна 325 гр",
			"productName" : "Тушонка Classo М'ясо Яловичина ніжна 325 гр",
			"unit" : "шт.",
			"baseUnit" : "шт.",
			"coefficient" : "1",
			"previousPrice" : "",
			"price" : "",
			"minCountUnit" : "18",
			"promotion" : "1",
			"imgSrc" : "https:\/\/olegeduc.github.io\/food-trade\/image\/classo-konservi\\classo-jalovichina-nizhna-325g.jpg",
			},
		"10" :  { 
			"category" : "Консерви м'ясні",
			"productCode" : "1889",
			"productFullName" : "Тушонка Classo М'ясо Яловичина ніжна 525 гр",
			"productName" : "Тушонка Classo М'ясо Яловичина ніжна 525 гр",
			"unit" : "шт.",
			"baseUnit" : "шт.",
			"coefficient" : "1",
			"previousPrice" : "",
			"price" : "",
			"minCountUnit" : "12",
			"promotion" : "1",
			"imgSrc" : "https:\/\/olegeduc.github.io\/food-trade\/image\/classo-konservi\\classo-jalovichina-nizhna-525g.jpg",
			},
		"11" :  { 
			"category" : "Консерви м'ясні",
			"productCode" : "1005",
			"productFullName" : "Тушкована свинина \"ПАН-ІВАН\" с\/б 500г.",
			"productName" : "Тушонка з свинини ПАН-ИВАН с\/б 500г.",
			"unit" : "шт.",
			"baseUnit" : "шт.",
			"coefficient" : "1",
			"previousPrice" : "",
			"price" : "",
			"minCountUnit" : "12",
			"promotion" : "1",
			"imgSrc" : "https:\/\/olegeduc.github.io\/food-trade\/image\/konservi-mjasnye\\tushonka-z-svinini-pan-ivan-sb-500g.jpg",
			},
	},
}



export const productCategorys = {
	"Konservi-m'jasni" : "Консерви м'ясні",
 }

export const anouns = []