// оновлено 13.03.25: 20:41:53.  Категория цены: Оптова //
export const products = {
	"focusProduct" : {
		"1-723"  :  { 
			"category" : "Олія",
			"productCode" : "723",
			"productFullName" : "Олія \"Бокарєв\" рафінована 700г.",
			"productName" : "Олія раф  Бокарев 700г.",
			"unit" : "шт.",
			"baseUnit" : "шт.",
			"coefficient" : "1",
			"previousPrice" : "47.9",
			"price" : "47.9",
			"minCountUnit" : "9",
			"promotion" : "1",
			"imgSrc" : "https:\/\/olegeduc.github.io\/food-trade\/image\/olija-bokarev-raf-760-ml.jpg",
			},
		"2-3223"  :  { 
			"category" : "Олія",
			"productCode" : "3223",
			"productFullName" : "Олія \"Гурман\" рафінована 2л.",
			"productName" : "Олія раф Гурман 2л.",
			"unit" : "шт.",
			"baseUnit" : "шт.",
			"coefficient" : "1",
			"previousPrice" : "109.9",
			"price" : "109.9",
			"minCountUnit" : "6",
			"promotion" : "1",
			"imgSrc" : "https:\/\/olegeduc.github.io\/food-trade\/image\/3223-olija-gurman-rafinovana-2l.jpg",
			},
	},
	"Olija" : {
		"1" :  { 
			"category" : "Олія",
			"productCode" : "1741",
			"productFullName" : "Олія \"Бокарєв\" нерафінована 1л",
			"productName" : "Олія Бокарев н\/р 1 л",
			"unit" : "шт.",
			"baseUnit" : "шт.",
			"coefficient" : "1",
			"previousPrice" : "0",
			"price" : "0",
			"minCountUnit" : "9",
			"promotion" : "1",
			"imgSrc" : "https:\/\/olegeduc.github.io\/food-trade\/image\/olyja-bokarev-neraf-1l.jpg",
			},
		"2" :  { 
			"category" : "Олія",
			"productCode" : "2369",
			"productFullName" : "Олія ТМ\"Бокарєв\" 3л. нерафінована",
			"productName" : "Олія Бокарев н\/р 3л.",
			"unit" : "шт.",
			"baseUnit" : "шт.",
			"coefficient" : "1",
			"previousPrice" : "0",
			"price" : "0",
			"minCountUnit" : "4",
			"promotion" : "1",
			"imgSrc" : "https:\/\/olegeduc.github.io\/food-trade\/image\/2369-olija-tm-bokarjev-3l-nerafinovana.jpg",
			},
		"3" :  { 
			"category" : "Олія",
			"productCode" : "1818",
			"productFullName" : "Олія \"Бокарєв\" нерафінована 5л",
			"productName" : "Олія Бокарев н\/р 5 л",
			"unit" : "шт.",
			"baseUnit" : "шт.",
			"coefficient" : "1",
			"previousPrice" : "0",
			"price" : "0",
			"minCountUnit" : "2",
			"promotion" : "1",
			"imgSrc" : "https:\/\/olegeduc.github.io\/food-trade\/image\/olija-bokarev-neraf-5-l.jpg",
			},
		"4" :  { 
			"category" : "Олія",
			"productCode" : "709",
			"productFullName" : "Олія \"Бокарєв\" нерафінована 700г",
			"productName" : "Олія Бокарев н\/р 700 г",
			"unit" : "шт.",
			"baseUnit" : "шт.",
			"coefficient" : "1",
			"previousPrice" : "0",
			"price" : "0",
			"minCountUnit" : "9",
			"promotion" : "1",
			"imgSrc" : "https:\/\/olegeduc.github.io\/food-trade\/image\/olija-bokarev-neraf-760-ml.jpg",
			},
		"5" :  { 
			"category" : "Олія",
			"productCode" : "3224",
			"productFullName" : "Олія \"Гурман\" нерафінована 2л.",
			"productName" : "Олія Гурман н\/р  2л.",
			"unit" : "шт.",
			"baseUnit" : "шт.",
			"coefficient" : "1",
			"previousPrice" : "0",
			"price" : "0",
			"minCountUnit" : "6",
			"promotion" : "1",
			"imgSrc" : "https:\/\/olegeduc.github.io\/food-trade\/image\/olija-gurman-neraf-2l.jpg",
			},
		"6" :  { 
			"category" : "Олія",
			"productCode" : "723",
			"productFullName" : "Олія \"Бокарєв\" рафінована 700г.",
			"productName" : "Олія раф  Бокарев 700г.",
			"unit" : "шт.",
			"baseUnit" : "шт.",
			"coefficient" : "1",
			"previousPrice" : "0",
			"price" : "0",
			"minCountUnit" : "9",
			"promotion" : "1",
			"imgSrc" : "https:\/\/olegeduc.github.io\/food-trade\/image\/olija-bokarev-raf-760-ml.jpg",
			},
		"7" :  { 
			"category" : "Олія",
			"productCode" : "1782",
			"productFullName" : "Олія \"Бокарєв\" рафінована 1л.",
			"productName" : "Олія раф Бокарев 1л.",
			"unit" : "шт.",
			"baseUnit" : "шт.",
			"coefficient" : "1",
			"previousPrice" : "0",
			"price" : "0",
			"minCountUnit" : "9",
			"promotion" : "1",
			"imgSrc" : "https:\/\/olegeduc.github.io\/food-trade\/image\/olyja-bokarev-raf-1l.jpg",
			},
		"8" :  { 
			"category" : "Олія",
			"productCode" : "729",
			"productFullName" : "Олія ТМ\"Бокарєв\" 3л. рафінована",
			"productName" : "Олія раф Бокарев 3 л.",
			"unit" : "шт.",
			"baseUnit" : "шт.",
			"coefficient" : "1",
			"previousPrice" : "0",
			"price" : "0",
			"minCountUnit" : "4",
			"promotion" : "1",
			"imgSrc" : "https:\/\/olegeduc.github.io\/food-trade\/image\/729-olija-tm-bokarjev-3l-rafinovana.jpg",
			},
		"9" :  { 
			"category" : "Олія",
			"productCode" : "1819",
			"productFullName" : "Олія \"Бокарєв\" рафінована 5л.",
			"productName" : "Олія раф Бокарев 5л.",
			"unit" : "шт.",
			"baseUnit" : "шт.",
			"coefficient" : "1",
			"previousPrice" : "0",
			"price" : "0",
			"minCountUnit" : "2",
			"promotion" : "1",
			"imgSrc" : "https:\/\/olegeduc.github.io\/food-trade\/image\/olyja-bokarev-raf-5l.jpg",
			},
		"10" :  { 
			"category" : "Олія",
			"productCode" : "3223",
			"productFullName" : "Олія \"Гурман\" рафінована 2л.",
			"productName" : "Олія раф Гурман 2л.",
			"unit" : "шт.",
			"baseUnit" : "шт.",
			"coefficient" : "1",
			"previousPrice" : "0",
			"price" : "0",
			"minCountUnit" : "6",
			"promotion" : "1",
			"imgSrc" : "https:\/\/olegeduc.github.io\/food-trade\/image\/3223-olija-gurman-rafinovana-2l.jpg",
			},
		"11" :  { 
			"category" : "Олія",
			"productCode" : "3273",
			"productFullName" : "Олія \"Гурман\" рафінована 3",
			"productName" : "Олія раф Гурман 3",
			"unit" : "шт.",
			"baseUnit" : "шт.",
			"coefficient" : "1",
			"previousPrice" : "0",
			"price" : "0",
			"minCountUnit" : "4",
			"promotion" : "1",
			"imgSrc" : "https:\/\/olegeduc.github.io\/food-trade\/image\/olyja-gurman-3l.jpg",
			},
		"12" :  { 
			"category" : "Олія",
			"productCode" : "4260",
			"productFullName" : "Олія рафінована ТМ\"Олівія\" 5л.",
			"productName" : "Олія раф Олівія 5л.",
			"unit" : "шт.",
			"baseUnit" : "шт.",
			"coefficient" : "1",
			"previousPrice" : "0",
			"price" : "0",
			"minCountUnit" : "4",
			"promotion" : "1",
			"imgSrc" : "https:\/\/olegeduc.github.io\/food-trade\/image\/4260-olija-rafinovana-tm-olivija-5l.jpg",
			},
		"13" :  { 
			"category" : "Олія",
			"productCode" : "4213",
			"productFullName" : "Олія соняшникова рафін. ТМ \"Сто пудов\" 1л.",
			"productName" : "Олія раф Стопудова 1 л.",
			"unit" : "шт.",
			"baseUnit" : "шт.",
			"coefficient" : "1",
			"previousPrice" : "0",
			"price" : "0",
			"minCountUnit" : "12",
			"promotion" : "1",
			"imgSrc" : "https:\/\/olegeduc.github.io\/food-trade\/image\/olija-raf-stopudova-1-l.jpg",
			},
	},
	"Konditers'ki-virobi" : {
		"14" :  { 
			"category" : "Кондитерські вироби",
			"productCode" : "38",
			"productFullName" : "Батончик \"Snickers\" арахіс в мол. шок. 50 г.",
			"productName" : "Батончик Сникерс арахіс в мол. шок. 50 г.",
			"unit" : "шт.",
			"baseUnit" : "шт.",
			"coefficient" : "1",
			"previousPrice" : "0",
			"price" : "0",
			"minCountUnit" : "40",
			"promotion" : "1",
			"imgSrc" : "https:\/\/olegeduc.github.io\/food-trade\/image\/snikers-50g.jpg",
			},
		"15" :  { 
			"category" : "Кондитерські вироби",
			"productCode" : "3614",
			"productFullName" : "Ваф. рулетики \"Ролло\" смак згущеного молока, 2,4 кг ТМ \"Golski\"",
			"productName" : "Ваф рулетики Ролло зі смаком згущеного молока, 2,4 кг Гольскі",
			"unit" : "кг.",
			"baseUnit" : "кг.",
			"coefficient" : "1",
			"previousPrice" : "0",
			"price" : "0",
			"minCountUnit" : "2.4",
			"promotion" : "1",
			"imgSrc" : "https:\/\/olegeduc.github.io\/food-trade\/image\/gol'ski\\gol'ski-rollo-prjazh-mol.jpg",
			},
		"16" :  { 
			"category" : "Кондитерські вироби",
			"productCode" : "3080",
			"productFullName" : "Ваф. рулетики \"Ролло\" смак пряженого молока, 2,4 кг ТМ \"Golski\"",
			"productName" : "Ваф рулетики Ролло зі смаком пряженого молока, 2,4 кг Гольскі",
			"unit" : "кг.",
			"baseUnit" : "кг.",
			"coefficient" : "1",
			"previousPrice" : "0",
			"price" : "0",
			"minCountUnit" : "2.4",
			"promotion" : "1",
			"imgSrc" : "https:\/\/olegeduc.github.io\/food-trade\/image\/gol'ski\\gol'ski-rollo-prjazh-mol.jpg",
			},
		"17" :  { 
			"category" : "Кондитерські вироби",
			"productCode" : "3500",
			"productFullName" : "Ваф. трубочки \"Мііо\" з начинкою смак пломбіру 2,3 кг ТМ \"Golski\"",
			"productName" : "Ваф трубочки Мііо з нач зі смаком пломбіру 2,3 кг Гольскі",
			"unit" : "кг.",
			"baseUnit" : "кг.",
			"coefficient" : "1",
			"previousPrice" : "0",
			"price" : "0",
			"minCountUnit" : "2.3",
			"promotion" : "1",
			"imgSrc" : "https:\/\/olegeduc.github.io\/food-trade\/image\/gol'ski\\goll'ski-miio-prjazhenogo-moloka.jpg",
			},
		"18" :  { 
			"category" : "Кондитерські вироби",
			"productCode" : "3615",
			"productFullName" : "Ваф. трубочки \"Мііо\" з нач смак пряженого мол. 2,3 кг ТМ \"Golski\"",
			"productName" : "Ваф трубочки Мііо з нач пряженого мол.  2,3 кг Гольскі",
			"unit" : "кг.",
			"baseUnit" : "кг.",
			"coefficient" : "1",
			"previousPrice" : "0",
			"price" : "0",
			"minCountUnit" : "2.3",
			"promotion" : "1",
			"imgSrc" : "https:\/\/olegeduc.github.io\/food-trade\/image\/gol'ski\\goll'ski-miio-prjazhenogo-moloka.jpg",
			},
		"19" :  { 
			"category" : "Кондитерські вироби",
			"productCode" : "94",
			"productFullName" : "Вафельні конуси ТМ \"LEKORNA\"",
			"productName" : "Вафельні конуси ЛЕКОРНА",
			"unit" : "шт.",
			"baseUnit" : "шт.",
			"coefficient" : "1",
			"previousPrice" : "0",
			"price" : "0",
			"minCountUnit" : "14",
			"promotion" : "1",
			"imgSrc" : "https:\/\/olegeduc.github.io\/food-trade\/image\/vafel'ni-konusi-lekorna-2.jpg",
			},
		"20" :  { 
			"category" : "Кондитерські вироби",
			"productCode" : "1358",
			"productFullName" : "Вафельні коржі великі ТМ \"LEKORNA\"",
			"productName" : "Вафельні коржі великі ЛЕКОРНА",
			"unit" : "шт.",
			"baseUnit" : "шт.",
			"coefficient" : "1",
			"previousPrice" : "0",
			"price" : "0",
			"minCountUnit" : "18",
			"promotion" : "1",
			"imgSrc" : "https:\/\/olegeduc.github.io\/food-trade\/image\/vafel'ni-korzhi-65g-velika.jpg",
			},
		"21" :  { 
			"category" : "Кондитерські вироби",
			"productCode" : "1333",
			"productFullName" : "Вафельні коржі великі ТМ \"LEKORNA\" веселка",
			"productName" : "Вафельні коржі великі ЛЕКОРНА веселка",
			"unit" : "шт.",
			"baseUnit" : "шт.",
			"coefficient" : "1",
			"previousPrice" : "0",
			"price" : "0",
			"minCountUnit" : "18",
			"promotion" : "1",
			"imgSrc" : "https:\/\/olegeduc.github.io\/food-trade\/image\/vafel'ni-korzhi-veselka-lekorna-140g-velika.jpg",
			},
		"22" :  { 
			"category" : "Кондитерські вироби",
			"productCode" : "97",
			"productFullName" : "Вафельні коржі малі (бризолі) ТМ \"LEKORNA\"",
			"productName" : "Вафельні коржі малі (бризолі) ЛЕКОРНА",
			"unit" : "шт.",
			"baseUnit" : "шт.",
			"coefficient" : "1",
			"previousPrice" : "0",
			"price" : "0",
			"minCountUnit" : "15",
			"promotion" : "1",
			"imgSrc" : "https:\/\/olegeduc.github.io\/food-trade\/image\/vafel'ni-korzhi-mali-lekorna.jpg",
			},
		"23" :  { 
			"category" : "Кондитерські вироби",
			"productCode" : "98",
			"productFullName" : "Вафельні кошики ТМ \"LEKORNA\"",
			"productName" : "Вафельні кошики ЛЕКОРНА",
			"unit" : "шт.",
			"baseUnit" : "шт.",
			"coefficient" : "1",
			"previousPrice" : "0",
			"price" : "0",
			"minCountUnit" : "26",
			"promotion" : "1",
			"imgSrc" : "https:\/\/olegeduc.github.io\/food-trade\/image\/vafel'ni-korzinki-lekorna-26-sht.jpg",
			},
		"24" :  { 
			"category" : "Кондитерські вироби",
			"productCode" : "100",
			"productFullName" : "Вафельні трубочки ТМ \"LEKORNA\"",
			"productName" : "Вафельні трубочки ЛЕКОРНА",
			"unit" : "шт.",
			"baseUnit" : "шт.",
			"coefficient" : "1",
			"previousPrice" : "0",
			"price" : "0",
			"minCountUnit" : "14",
			"promotion" : "1",
			"imgSrc" : "https:\/\/olegeduc.github.io\/food-trade\/image\/vafel'ni-trubochki-lekorna-26-sht.jpg",
			},
		"25" :  { 
			"category" : "Кондитерські вироби",
			"productCode" : "3943",
			"productFullName" : "Вафлі Артек Сонячний 3 кг.",
			"productName" : "Вафлі Артек Сонячний 3 кг.",
			"unit" : "кг.",
			"baseUnit" : "кг.",
			"coefficient" : "1",
			"previousPrice" : "0",
			"price" : "0",
			"minCountUnit" : "3",
			"promotion" : "1",
			"imgSrc" : "https:\/\/olegeduc.github.io\/food-trade\/image\/nektar\\vafli-nektar-artek-sonjachn-3kg.jpg",
			},
		"26" :  { 
			"category" : "Кондитерські вироби",
			"productCode" : "1377",
			"productFullName" : "Вафлі Артек Сонячний 70 г.",
			"productName" : "Вафлі Артек Сонячний 70 г.",
			"unit" : "шт.",
			"baseUnit" : "шт.",
			"coefficient" : "1",
			"previousPrice" : "0",
			"price" : "0",
			"minCountUnit" : "40",
			"promotion" : "1",
			"imgSrc" : "https:\/\/olegeduc.github.io\/food-trade\/image\/nektar\\vafli-artek-sonjachn-nektar.jpg",
			},
		"27" :  { 
			"category" : "Кондитерські вироби",
			"productCode" : "1572",
			"productFullName" : "Вафлі \"Артек-Європейський\" 4 кг.",
			"productName" : "Вафлі Артек-Європейський 4 кг. ХЗПТ",
			"unit" : "кг.",
			"baseUnit" : "кг.",
			"coefficient" : "1",
			"previousPrice" : "0",
			"price" : "0",
			"minCountUnit" : "4",
			"promotion" : "1",
			"imgSrc" : "https:\/\/olegeduc.github.io\/food-trade\/image\/har'kov-hzpt\\vafli-artek-jevropejskij-4-kg-hzpt.jpg",
			},
		"28" :  { 
			"category" : "Кондитерські вироби",
			"productCode" : "4055",
			"productFullName" : "Вафлі \"Молочні\" 70 г.",
			"productName" : "Вафлі Молочні 70 г.",
			"unit" : "шт.",
			"baseUnit" : "шт.",
			"coefficient" : "1",
			"previousPrice" : "0",
			"price" : "0",
			"minCountUnit" : "40",
			"promotion" : "1",
			"imgSrc" : "https:\/\/olegeduc.github.io\/food-trade\/image\/nektar\\vafli-molochni-70-nektar.jpg",
			},
		"29" :  { 
			"category" : "Кондитерські вироби",
			"productCode" : "3439",
			"productFullName" : "Карамель ТМ \"BAYAN SULU\" грейпфрут 1 кг.",
			"productName" : "Карамель  BS грейпфрут 1 кг.",
			"unit" : "шт.",
			"baseUnit" : "шт.",
			"coefficient" : "1",
			"previousPrice" : "0",
			"price" : "0",
			"minCountUnit" : "1",
			"promotion" : "1",
			"imgSrc" : "https:\/\/olegeduc.github.io\/food-trade\/image\/bayan-sulu\\3439-karamel-tm-bayan-sulu-grejpfrut-1-kg.jpg",
			},
		"30" :  { 
			"category" : "Кондитерські вироби",
			"productCode" : "3457",
			"productFullName" : "Карамель ТМ \"BAYAN SULU\" Mini-Fruit асс. 1 кг",
			"productName" : "Карамель  Міні BS Fruit  асс. 1 кг.",
			"unit" : "шт.",
			"baseUnit" : "кг.",
			"coefficient" : "1",
			"previousPrice" : "0",
			"price" : "0",
			"minCountUnit" : "1",
			"promotion" : "1",
			"imgSrc" : "https:\/\/olegeduc.github.io\/food-trade\/image\/bayan-sulu\\3457-karamel-tm-bayan-sulu-mini-fruit-ass-1-kg.jpg",
			},
		"31" :  { 
			"category" : "Кондитерські вироби",
			"productCode" : "3440",
			"productFullName" : "Карамель ТМ \"BAYAN SULU\" апельсин 1 кг.",
			"productName" : "Карамель BS апельсин 1 кг.",
			"unit" : "шт.",
			"baseUnit" : "шт.",
			"coefficient" : "1",
			"previousPrice" : "0",
			"price" : "0",
			"minCountUnit" : "1",
			"promotion" : "1",
			"imgSrc" : "https:\/\/olegeduc.github.io\/food-trade\/image\/bayan-sulu\\3440-karamel-tm-bayan-sulu-apelsin-1-kg.jpg",
			},
		"32" :  { 
			"category" : "Кондитерські вироби",
			"productCode" : "3441",
			"productFullName" : "Карамель ТМ \"BAYAN SULU\" банан 1 кг.",
			"productName" : "Карамель BS банан 1 кг.",
			"unit" : "шт.",
			"baseUnit" : "шт.",
			"coefficient" : "1",
			"previousPrice" : "0",
			"price" : "0",
			"minCountUnit" : "1",
			"promotion" : "1",
			"imgSrc" : "https:\/\/olegeduc.github.io\/food-trade\/image\/bayan-sulu\\3441-karamel-tm-bayan-sulu-banan-1-kg.jpg",
			},
		"33" :  { 
			"category" : "Кондитерські вироби",
			"productCode" : "3448",
			"productFullName" : "Карамель ТМ \"BAYAN SULU\" яблуко 1 кг.",
			"productName" : "Карамель BS яблуко 1 кг.",
			"unit" : "шт.",
			"baseUnit" : "шт.",
			"coefficient" : "1",
			"previousPrice" : "0",
			"price" : "0",
			"minCountUnit" : "1",
			"promotion" : "1",
			"imgSrc" : "https:\/\/olegeduc.github.io\/food-trade\/image\/bayan-sulu\\3448-karamel-tm-bayan-sulu-jabluko-1-kg.jpg",
			},
		"34" :  { 
			"category" : "Кондитерські вироби",
			"productCode" : "468",
			"productFullName" : "Коржі ТМ\"Мерсі\" Медовий 500 гр.",
			"productName" : "Коржі Мерсі Медовий 500 гр.",
			"unit" : "шт.",
			"baseUnit" : "шт.",
			"coefficient" : "1",
			"previousPrice" : "0",
			"price" : "0",
			"minCountUnit" : "12",
			"promotion" : "1",
			"imgSrc" : "https:\/\/olegeduc.github.io\/food-trade\/image\/mersi-medovik-2.jpg",
			},
		"35" :  { 
			"category" : "Кондитерські вироби",
			"productCode" : "469",
			"productFullName" : "Коржі ТМ\"Мерсі\" Наполеон 400 гр.",
			"productName" : "Коржі Мерсі Наполеон 400 гр.",
			"unit" : "шт.",
			"baseUnit" : "шт.",
			"coefficient" : "1",
			"previousPrice" : "0",
			"price" : "0",
			"minCountUnit" : "12",
			"promotion" : "1",
			"imgSrc" : "https:\/\/olegeduc.github.io\/food-trade\/image\/mersi-napoleon-2.jpg",
			},
		"36" :  { 
			"category" : "Кондитерські вироби",
			"productCode" : "3737",
			"productFullName" : "Трубочки кукурудзяні \"Boo sticks Maxi\" з молочним смаком 1,3 кг",
			"productName" : "Трубочки кукурудзяні Boo sticks Maxi з молочним смаком 1,3 кг",
			"unit" : "кг.",
			"baseUnit" : "кг.",
			"coefficient" : "1",
			"previousPrice" : "0",
			"price" : "0",
			"minCountUnit" : "1.3",
			"promotion" : "1",
			"imgSrc" : "https:\/\/olegeduc.github.io\/food-trade\/image\/nektar\\trubochki-kukurudz-boo-sticks-maxi-z-mol-smak-1-3-kg.jpg",
			},
		"37" :  { 
			"category" : "Кондитерські вироби",
			"productCode" : "3738",
			"productFullName" : "Трубочки кукурудзяні \"Boo sticks Maxi\" з шоколадним смаком 1,3 кг",
			"productName" : "Трубочки кукурудзяні Boo sticks Maxi з шоколадним смаком 1,3 кг",
			"unit" : "кг.",
			"baseUnit" : "кг.",
			"coefficient" : "1",
			"previousPrice" : "0",
			"price" : "0",
			"minCountUnit" : "1.3",
			"promotion" : "1",
			"imgSrc" : "https:\/\/olegeduc.github.io\/food-trade\/image\/nektar\\trubochki-kukurudz-boo-sticks-maxi-z-shok-smak-1-3-kg-2.jpg",
			},
		"38" :  { 
			"category" : "Кондитерські вироби",
			"productCode" : "3462",
			"productFullName" : "Трубочки кукурудзяні \"Boo sticks\" з молочним смаком 2 кг",
			"productName" : "Трубочки кукурудзяні Boo sticks з молочним смаком 2 кг",
			"unit" : "кг.",
			"baseUnit" : "кг.",
			"coefficient" : "1",
			"previousPrice" : "0",
			"price" : "0",
			"minCountUnit" : "2",
			"promotion" : "1",
			"imgSrc" : "https:\/\/olegeduc.github.io\/food-trade\/image\/trubochki-kukurudzjani-boo-sticks-z-molochnim-smakom-2-kg.jpg",
			},
		"39" :  { 
			"category" : "Кондитерські вироби",
			"productCode" : "3463",
			"productFullName" : "Трубочки кукурудзяні \"Boo sticks\" з смаком тірамісу 2 кг",
			"productName" : "Трубочки кукурудзяні Boo sticks з смаком тірамісу 2 кг",
			"unit" : "кг.",
			"baseUnit" : "кг.",
			"coefficient" : "1",
			"previousPrice" : "0",
			"price" : "0",
			"minCountUnit" : "2",
			"promotion" : "1",
			"imgSrc" : "https:\/\/olegeduc.github.io\/food-trade\/image\/nektar\\trubochki-kukurudzjani-boo-sticks-z-smakom-tiramisu-2-kg.jpg",
			},
		"40" :  { 
			"category" : "Кондитерські вироби",
			"productCode" : "4130",
			"productFullName" : "Халва ТМ\"Сонечко\" 70 г.",
			"productName" : "Халва  Сонечко 70 г.",
			"unit" : "шт.",
			"baseUnit" : "шт.",
			"coefficient" : "1",
			"previousPrice" : "0",
			"price" : "0",
			"minCountUnit" : "5",
			"promotion" : "1",
			"imgSrc" : "https:\/\/olegeduc.github.io\/food-trade\/image\/halva-tm-sonechko-70-g.jpg",
			},
		"41" :  { 
			"category" : "Кондитерські вироби",
			"productCode" : "4131",
			"productFullName" : "Халва ТМ\"Сонечко\" в шоколадній глазурі 85 г.",
			"productName" : "Халва  Сонечко в шоколаді 85 г.",
			"unit" : "шт.",
			"baseUnit" : "шт.",
			"coefficient" : "1",
			"previousPrice" : "0",
			"price" : "0",
			"minCountUnit" : "5",
			"promotion" : "1",
			"imgSrc" : "https:\/\/olegeduc.github.io\/food-trade\/image\/halva-tm-sonechko-v-shokoladnij-glazuri-85-g.jpg",
			},
		"42" :  { 
			"category" : "Кондитерські вироби",
			"productCode" : "4148",
			"productFullName" : "Халва ТМ\"Сонечко\" зебра з какао 70г.",
			"productName" : "Халва  Сонечко ЗЕБРА 70 г.",
			"unit" : "шт.",
			"baseUnit" : "шт.",
			"coefficient" : "1",
			"previousPrice" : "0",
			"price" : "0",
			"minCountUnit" : "5",
			"promotion" : "1",
			"imgSrc" : "https:\/\/olegeduc.github.io\/food-trade\/image\/halva-tm-sonechko-zebra-z-kakao-70g.jpg",
			},
		"43" :  { 
			"category" : "Кондитерські вироби",
			"productCode" : "2837",
			"productFullName" : "Халва ТМ \"Жадана\" 200 г.",
			"productName" : "Халва Жадана 200 г.",
			"unit" : "шт.",
			"baseUnit" : "шт.",
			"coefficient" : "1",
			"previousPrice" : "0",
			"price" : "0",
			"minCountUnit" : "20",
			"promotion" : "1",
			"imgSrc" : "https:\/\/olegeduc.github.io\/food-trade\/image\/halva-zhadana-200-g.jpg",
			},
		"44" :  { 
			"category" : "Кондитерські вироби",
			"productCode" : "1387",
			"productFullName" : "Халва ТМ \"Жадана\" 330 г.",
			"productName" : "Халва Жадана 330 г.",
			"unit" : "шт.",
			"baseUnit" : "шт.",
			"coefficient" : "1",
			"previousPrice" : "0",
			"price" : "0",
			"minCountUnit" : "12",
			"promotion" : "1",
			"imgSrc" : "https:\/\/olegeduc.github.io\/food-trade\/image\/halva-zhadana-330-g.jpg",
			},
		"45" :  { 
			"category" : "Кондитерські вироби",
			"productCode" : "1474",
			"productFullName" : "Халва ТМ \"Жадана\" 330 г. з ваніліном",
			"productName" : "Халва Жадана 330 г. з ваніліном",
			"unit" : "шт.",
			"baseUnit" : "шт.",
			"coefficient" : "1",
			"previousPrice" : "0",
			"price" : "0",
			"minCountUnit" : "12",
			"promotion" : "1",
			"imgSrc" : "https:\/\/olegeduc.github.io\/food-trade\/image\/halva-zhadana-330-g-z-vanilinom.jpg",
			},
		"46" :  { 
			"category" : "Кондитерські вироби",
			"productCode" : "1020",
			"productFullName" : "Халва ТМ \"Жадана\" 5кг.",
			"productName" : "Халва Жадана 5кг.",
			"unit" : "кг.",
			"baseUnit" : "кг.",
			"coefficient" : "1",
			"previousPrice" : "0",
			"price" : "0",
			"minCountUnit" : "5",
			"promotion" : "1",
			"imgSrc" : "https:\/\/olegeduc.github.io\/food-trade\/image\/halva-zhadana-5.jpg",
			},
		"47" :  { 
			"category" : "Кондитерські вироби",
			"productCode" : "1711",
			"productFullName" : "Халва ТМ \"Жадана\" шоколадно-ванільна 5кг. \"Зебра\"",
			"productName" : "Халва Жадана 5кг. Зебра",
			"unit" : "кг.",
			"baseUnit" : "кг.",
			"coefficient" : "1",
			"previousPrice" : "0",
			"price" : "0",
			"minCountUnit" : "5",
			"promotion" : "1",
			"imgSrc" : "https:\/\/olegeduc.github.io\/food-trade\/image\/halva-zhadana-5-zebra.jpg",
			},
		"48" :  { 
			"category" : "Кондитерські вироби",
			"productCode" : "1592",
			"productFullName" : "Халва ТМ \"Жадана\" 900 г.",
			"productName" : "Халва Жадана 900 г.",
			"unit" : "шт.",
			"baseUnit" : "шт.",
			"coefficient" : "1",
			"previousPrice" : "0",
			"price" : "0",
			"minCountUnit" : "5",
			"promotion" : "1",
			"imgSrc" : "https:\/\/olegeduc.github.io\/food-trade\/image\/halva-zhadana-900g.jpg",
			},
		"49" :  { 
			"category" : "Кондитерські вироби",
			"productCode" : "1475",
			"productFullName" : "Халва ТМ \"Жадана\" з горіхами 330 г.",
			"productName" : "Халва Жадана з горіхами 330 г.",
			"unit" : "шт.",
			"baseUnit" : "шт.",
			"coefficient" : "1",
			"previousPrice" : "0",
			"price" : "0",
			"minCountUnit" : "12",
			"promotion" : "1",
			"imgSrc" : "https:\/\/olegeduc.github.io\/food-trade\/image\/halva-zhadana-330-g-z-gorihami.jpg",
			},
		"50" :  { 
			"category" : "Кондитерські вироби",
			"productCode" : "3846",
			"productFullName" : "Цукерки \"Coffe art\" глазур 2,2 кг. ТМ \"Golski\"",
			"productName" : "Цук Coffe art глазур 2,2 кг. Гольскі",
			"unit" : "кг.",
			"baseUnit" : "кг.",
			"coefficient" : "1",
			"previousPrice" : "0",
			"price" : "0",
			"minCountUnit" : "2.2",
			"promotion" : "1",
			"imgSrc" : "https:\/\/olegeduc.github.io\/food-trade\/image\/gol'ski\\gol'ski-coffee-art.jpg",
			},
		"51" :  { 
			"category" : "Кондитерські вироби",
			"productCode" : "3563",
			"productFullName" : "Цукерки \"Crema Rosso\" глазур 1.7 кг. ТМ \"Golski\"",
			"productName" : "Цук Crema Rosso глазур 1.7 кг. Гольскі",
			"unit" : "кг.",
			"baseUnit" : "кг.",
			"coefficient" : "1",
			"previousPrice" : "0",
			"price" : "0",
			"minCountUnit" : "1.7",
			"promotion" : "1",
			"imgSrc" : "https:\/\/olegeduc.github.io\/food-trade\/image\/gol'ski\\gol'sk-crema-rosso.jpg",
			},
		"52" :  { 
			"category" : "Кондитерські вироби",
			"productCode" : "3499",
			"productFullName" : "Цукерки \"Crispini\" глазур 2.2 кг.ТМ \"Golski\"",
			"productName" : "Цук Crispini глазур 2.2 кг. Гольскі",
			"unit" : "кг.",
			"baseUnit" : "кг.",
			"coefficient" : "1",
			"previousPrice" : "0",
			"price" : "0",
			"minCountUnit" : "2.2",
			"promotion" : "1",
			"imgSrc" : "https:\/\/olegeduc.github.io\/food-trade\/image\/gol'ski\\gol'ski-grispini.jpg",
			},
		"53" :  { 
			"category" : "Кондитерські вироби",
			"productCode" : "3921",
			"productFullName" : "Цукерки \"Para Truff\" глазур 1,5 кг.ТМ \"Golski\"",
			"productName" : "Цук Para Truff глазур 1,5 кг. Гольскі",
			"unit" : "кг.",
			"baseUnit" : "кг.",
			"coefficient" : "1",
			"previousPrice" : "0",
			"price" : "0",
			"minCountUnit" : "1.5",
			"promotion" : "1",
			"imgSrc" : "https:\/\/olegeduc.github.io\/food-trade\/image\/gol'ski\\cuk-para-truff-glazur-15-kggolski.jpg",
			},
		"54" :  { 
			"category" : "Кондитерські вироби",
			"productCode" : "3942",
			"productFullName" : "Цукерки \"Para Truff Nut\" глазур 1,5 кг.ТМ \"Golski\"",
			"productName" : "Цук Para Truff НАТ 1,5 кг. Гольскі",
			"unit" : "кг.",
			"baseUnit" : "кг.",
			"coefficient" : "1",
			"previousPrice" : "0",
			"price" : "0",
			"minCountUnit" : "1.5",
			"promotion" : "1",
			"imgSrc" : "https:\/\/olegeduc.github.io\/food-trade\/image\/gol'ski\\gol'ski-paratruff-nut.jpg",
			},
		"55" :  { 
			"category" : "Кондитерські вироби",
			"productCode" : "3521",
			"productFullName" : "Цукерки \"Piccolo\" згущене молоко глазур 1.7 кг. ТМ \"Golski\"",
			"productName" : "Цук Piccolo згущене молоко глазур 1.7 кг. Гольскі",
			"unit" : "кг.",
			"baseUnit" : "кг.",
			"coefficient" : "1",
			"previousPrice" : "0",
			"price" : "0",
			"minCountUnit" : "1.7",
			"promotion" : "1",
			"imgSrc" : "https:\/\/olegeduc.github.io\/food-trade\/image\/gol'ski\\gol'ski-pikolo-zguschene-moloko.jpg",
			},
		"56" :  { 
			"category" : "Кондитерські вироби",
			"productCode" : "3533",
			"productFullName" : "Цукерки \"Piccolo\" кавовий Трюфель глазур 1.7 кг. ТМ \"Golski\"",
			"productName" : "Цук Piccolo кавовий Трюфель глазур 1.7 кг. Гольскі",
			"unit" : "кг.",
			"baseUnit" : "кг.",
			"coefficient" : "1",
			"previousPrice" : "0",
			"price" : "0",
			"minCountUnit" : "1.7",
			"promotion" : "1",
			"imgSrc" : "https:\/\/olegeduc.github.io\/food-trade\/image\/gol'ski\\gol'ski-pikolo-kavovij-trjufel'.jpg",
			},
		"57" :  { 
			"category" : "Кондитерські вироби",
			"productCode" : "3532",
			"productFullName" : "Цукерки \"Piccolo\" лісовий горіх глазур 1.7 кг. ТМ \"Golski\"",
			"productName" : "Цук Piccolo лісовий горіх глазур 1.7 кг. Гольскі",
			"unit" : "кг.",
			"baseUnit" : "кг.",
			"coefficient" : "1",
			"previousPrice" : "0",
			"price" : "0",
			"minCountUnit" : "1.7",
			"promotion" : "1",
			"imgSrc" : "https:\/\/olegeduc.github.io\/food-trade\/image\/gol'ski\\gol'ski-pikolo-lisgorih.jpg",
			},
		"58" :  { 
			"category" : "Кондитерські вироби",
			"productCode" : "3069",
			"productFullName" : "Цукерки \"Sherwood\" глазур 2.2 кг.ТМ \"Golski\"",
			"productName" : "Цук Sherwood глазур 2.2 кг. Гольскі",
			"unit" : "кг.",
			"baseUnit" : "кг.",
			"coefficient" : "1",
			"previousPrice" : "0",
			"price" : "0",
			"minCountUnit" : "2.2",
			"promotion" : "1",
			"imgSrc" : "https:\/\/olegeduc.github.io\/food-trade\/image\/gol'ski\\gol'ski-shervud.jpg",
			},
		"59" :  { 
			"category" : "Кондитерські вироби",
			"productCode" : "3295",
			"productFullName" : "Цукерки \"Truffel\" глазур 2 кг.ТМ \"Golski\"",
			"productName" : "Цук Truffel глазур 2 кг. Гольскі",
			"unit" : "кг.",
			"baseUnit" : "кг.",
			"coefficient" : "1",
			"previousPrice" : "0",
			"price" : "0",
			"minCountUnit" : "2",
			"promotion" : "1",
			"imgSrc" : "https:\/\/olegeduc.github.io\/food-trade\/image\/gol'ski\\gol'ski-trjufel'.jpg",
			},
		"60" :  { 
			"category" : "Кондитерські вироби",
			"productCode" : "3339",
			"productFullName" : "Цукерки \"Truffel milk\" 2 кг. ТМ \"Golski\"",
			"productName" : "Цук Truffel мілк 2 кг.Гольскі",
			"unit" : "кг.",
			"baseUnit" : "кг.",
			"coefficient" : "1",
			"previousPrice" : "0",
			"price" : "0",
			"minCountUnit" : "2",
			"promotion" : "1",
			"imgSrc" : "https:\/\/olegeduc.github.io\/food-trade\/image\/gol'ski\\cuk-truffel-milk-2-kggolski.jpg",
			},
		"61" :  { 
			"category" : "Кондитерські вироби",
			"productCode" : "3107",
			"productFullName" : "Цукерки \"AMERICANA\" глазур 2 кг.ТМ \"Golski\"",
			"productName" : "Цук Амерікана глазур 2 кг. Гольскі",
			"unit" : "кг.",
			"baseUnit" : "кг.",
			"coefficient" : "1",
			"previousPrice" : "0",
			"price" : "0",
			"minCountUnit" : "2",
			"promotion" : "1",
			"imgSrc" : "https:\/\/olegeduc.github.io\/food-trade\/image\/gol'ski\\gol'ski-amerikana.jpg",
			},
		"62" :  { 
			"category" : "Кондитерські вироби",
			"productCode" : "3508",
			"productFullName" : "Цукерки \"Бабусині смаколики\" глазур 2,2 кг.Golski",
			"productName" : "Цук Бабусині смаколики глазур 2,2 кг.Гольскі",
			"unit" : "кг.",
			"baseUnit" : "кг.",
			"coefficient" : "1",
			"previousPrice" : "0",
			"price" : "0",
			"minCountUnit" : "2.2",
			"promotion" : "1",
			"imgSrc" : "https:\/\/olegeduc.github.io\/food-trade\/image\/gol'ski\\gol'ski-babusini-smakoliki.jpg",
			},
		"63" :  { 
			"category" : "Кондитерські вироби",
			"productCode" : "3845",
			"productFullName" : "Цукерки \"Білочка \" глазур 2,2 кг.ТМ \"Golski\"",
			"productName" : "Цук Білочка глазур 2,2 кг. Гольскі",
			"unit" : "кг.",
			"baseUnit" : "кг.",
			"coefficient" : "1",
			"previousPrice" : "0",
			"price" : "0",
			"minCountUnit" : "2.2",
			"promotion" : "1",
			"imgSrc" : "https:\/\/olegeduc.github.io\/food-trade\/image\/gol'ski\\gol'ski-bilochka.jpg",
			},
		"64" :  { 
			"category" : "Кондитерські вироби",
			"productCode" : "1914",
			"productFullName" : "Цукерки вафельні \"Казковий  Гулівер\" 3 кг. В\/Ц",
			"productName" : "Цук ваф  В\/Ц Казковий  Гулівер 3 кг.",
			"unit" : "кг.",
			"baseUnit" : "кг.",
			"coefficient" : "1",
			"previousPrice" : "0",
			"price" : "0",
			"minCountUnit" : "3",
			"promotion" : "1",
			"imgSrc" : "https:\/\/olegeduc.github.io\/food-trade\/image\/nektar\\nektar-kazkovij-guliver.jpg",
			},
		"65" :  { 
			"category" : "Кондитерські вироби",
			"productCode" : "2494",
			"productFullName" : "Цукерки вафельні \"Ананас\" фл\/пак, екран 2 кг",
			"productName" : "Цук ваф Ананас фл\/пак, экран 2 кг",
			"unit" : "кг.",
			"baseUnit" : "кг.",
			"coefficient" : "1",
			"previousPrice" : "0",
			"price" : "0",
			"minCountUnit" : "2",
			"promotion" : "1",
			"imgSrc" : "https:\/\/olegeduc.github.io\/food-trade\/image\/har'kov-hzpt\\cuk-vaf-ananas-hzpt.jpg",
			},
		"66" :  { 
			"category" : "Кондитерські вироби",
			"productCode" : "4117",
			"productFullName" : "Цукерки вафельні \"Асорті\" М\\Ц 1 кг.",
			"productName" : "Цук ваф Асорті М\\Ц 1 кг.",
			"unit" : "кг.",
			"baseUnit" : "кг.",
			"coefficient" : "1",
			"previousPrice" : "0",
			"price" : "0",
			"minCountUnit" : "1",
			"promotion" : "1",
			"imgSrc" : "https:\/\/olegeduc.github.io\/food-trade\/image\/har'kov-hzpt\\cuk-vaf-asorti-mc-1-kg.jpg",
			},
		"67" :  { 
			"category" : "Кондитерські вироби",
			"productCode" : "1604",
			"productFullName" : "Цукерки вафельні \"Асорті мультики\" фл\/пак, екран 2,5 к",
			"productName" : "Цук ваф Ассорти мультики фл\/пак, экран 2,5 к",
			"unit" : "кг.",
			"baseUnit" : "кг.",
			"coefficient" : "1",
			"previousPrice" : "0",
			"price" : "0",
			"minCountUnit" : "2.5",
			"promotion" : "1",
			"imgSrc" : "https:\/\/olegeduc.github.io\/food-trade\/image\/har'kov-hzpt\\cuk-vaf-assorti-multiki-flpak-jekran-25-k.jpg",
			},
		"68" :  { 
			"category" : "Кондитерські вироби",
			"productCode" : "1828",
			"productFullName" : "Цукерки вафельні \"Асорті Ретро\" фл\/пак, екран 2 кг",
			"productName" : "Цук ваф Ассорти Ретро фл\/пак, экран 2 кг",
			"unit" : "кг.",
			"baseUnit" : "кг.",
			"coefficient" : "1",
			"previousPrice" : "0",
			"price" : "0",
			"minCountUnit" : "2",
			"promotion" : "1",
			"imgSrc" : "https:\/\/olegeduc.github.io\/food-trade\/image\/har'kov-hzpt\\cuk-vaf-asorti-retro-hzpt.jpg",
			},
		"69" :  { 
			"category" : "Кондитерські вироби",
			"productCode" : "1994",
			"productFullName" : "Цукерки вафельні \"Білочка\" фл\/пак, екран 2 кг",
			"productName" : "Цук ваф Білочка фл\/пак, экран 2 кг",
			"unit" : "кг.",
			"baseUnit" : "кг.",
			"coefficient" : "1",
			"previousPrice" : "0",
			"price" : "0",
			"minCountUnit" : "2",
			"promotion" : "1",
			"imgSrc" : "https:\/\/olegeduc.github.io\/food-trade\/image\/har'kov-hzpt\\cuk-vaf-bilochka-hzpt.jpg",
			},
		"70" :  { 
			"category" : "Кондитерські вироби",
			"productCode" : "3371",
			"productFullName" : "Цукерки вафельні \"Гулівер\" фл\/пак, екран 2,5 кг",
			"productName" : "Цук ваф Гулівер фл\/пак, экран 2,5 кг",
			"unit" : "кг.",
			"baseUnit" : "кг.",
			"coefficient" : "1",
			"previousPrice" : "0",
			"price" : "0",
			"minCountUnit" : "2.5",
			"promotion" : "1",
			"imgSrc" : "https:\/\/olegeduc.github.io\/food-trade\/image\/har'kov-hzpt\\cuk-vaf-guliver-hzpt.jpg",
			},
		"71" :  { 
			"category" : "Кондитерські вироби",
			"productCode" : "1911",
			"productFullName" : "Цукерки вафельні \"Для Білосніжки\" М\/Ц 3 кг.",
			"productName" : "Цук ваф Для Білосніжки М\/Ц 3 кг.",
			"unit" : "кг.",
			"baseUnit" : "кг.",
			"coefficient" : "1",
			"previousPrice" : "0",
			"price" : "0",
			"minCountUnit" : "3",
			"promotion" : "1",
			"imgSrc" : "https:\/\/olegeduc.github.io\/food-trade\/image\/nektar\\nektar-dlja-bilosnizhkii.jpg",
			},
		"72" :  { 
			"category" : "Кондитерські вироби",
			"productCode" : "1913",
			"productFullName" : "Цукерки вафельні \"Для Вінні Пуха\" М\/Ц 3 кг.",
			"productName" : "Цук ваф Для Вінні Пуха М\/Ц 3 кг.",
			"unit" : "кг.",
			"baseUnit" : "кг.",
			"coefficient" : "1",
			"previousPrice" : "0",
			"price" : "0",
			"minCountUnit" : "3",
			"promotion" : "1",
			"imgSrc" : "https:\/\/olegeduc.github.io\/food-trade\/image\/nektar\\nektar-dlja-vinni-puha.jpg",
			},
		"73" :  { 
			"category" : "Кондитерські вироби",
			"productCode" : "1909",
			"productFullName" : "Цукерки вафельні \"Для Попелюшки\" М\/Ц 3 кг.",
			"productName" : "Цук ваф Для Попелюшки М\/Ц 3 кг.",
			"unit" : "кг.",
			"baseUnit" : "кг.",
			"coefficient" : "1",
			"previousPrice" : "0",
			"price" : "0",
			"minCountUnit" : "3",
			"promotion" : "1",
			"imgSrc" : "https:\/\/olegeduc.github.io\/food-trade\/image\/nektar\\nektar-dlja-popeljushkii.jpg",
			},
		"74" :  { 
			"category" : "Кондитерські вироби",
			"productCode" : "1908",
			"productFullName" : "Цукерки вафельні \"Для Червоної Шапочки\" М\/Ц 3 кг.",
			"productName" : "Цук ваф Для Червоної Шапочки М\/Ц 3 кг.",
			"unit" : "кг.",
			"baseUnit" : "кг.",
			"coefficient" : "1",
			"previousPrice" : "0",
			"price" : "0",
			"minCountUnit" : "3",
			"promotion" : "1",
			"imgSrc" : "https:\/\/olegeduc.github.io\/food-trade\/image\/nektar\\nektar-dlja-chervonoi-shapochki.jpg",
			},
		"75" :  { 
			"category" : "Кондитерські вироби",
			"productCode" : "2117",
			"productFullName" : "Цукерки вафельні \"Кара-кум\" фл\/пак, екран 2 кг",
			"productName" : "Цук ваф Кара-кум фл\/пак, экран 2 кг",
			"unit" : "кг.",
			"baseUnit" : "кг.",
			"coefficient" : "1",
			"previousPrice" : "0",
			"price" : "0",
			"minCountUnit" : "2",
			"promotion" : "1",
			"imgSrc" : "https:\/\/olegeduc.github.io\/food-trade\/image\/har'kov-hzpt\\cuk-vaf-kara-kum-hzpt.jpg",
			},
		"76" :  { 
			"category" : "Кондитерські вироби",
			"productCode" : "2133",
			"productFullName" : "Цукерки вафельні \"Червоний мак\" фл\/пак, екран 2 кг",
			"productName" : "Цук ваф Красний мак фл\/пак, экран 2 кг",
			"unit" : "кг.",
			"baseUnit" : "кг.",
			"coefficient" : "1",
			"previousPrice" : "0",
			"price" : "0",
			"minCountUnit" : "2",
			"promotion" : "1",
			"imgSrc" : "https:\/\/olegeduc.github.io\/food-trade\/image\/har'kov-hzpt\\cuk-vaf-chervonij-mak-hzpt.jpg",
			},
		"77" :  { 
			"category" : "Кондитерські вироби",
			"productCode" : "1982",
			"productFullName" : "Цукерки вафельні \"Мишка клишоногий\" фл\/пак екран 2 к",
			"productName" : "Цук ваф Мишка косолапий фл\/пак, экран 2 к",
			"unit" : "кг.",
			"baseUnit" : "кг.",
			"coefficient" : "1",
			"previousPrice" : "0",
			"price" : "0",
			"minCountUnit" : "2",
			"promotion" : "1",
			"imgSrc" : "https:\/\/olegeduc.github.io\/food-trade\/image\/har'kov-hzpt\\cuk-vaf-mishka-klishonogij-hzpt.jpg",
			},
		"78" :  { 
			"category" : "Кондитерські вироби",
			"productCode" : "1520",
			"productFullName" : "Цукерки вафельні \"Свинка Пеппа\" фл\/пак, екран 2,5 кг",
			"productName" : "Цук ваф Свинка Пеппа фл\/пак, экран 2,5 кг",
			"unit" : "кг.",
			"baseUnit" : "кг.",
			"coefficient" : "1",
			"previousPrice" : "0",
			"price" : "0",
			"minCountUnit" : "2.5",
			"promotion" : "1",
			"imgSrc" : "https:\/\/olegeduc.github.io\/food-trade\/image\/har'kov-hzpt\\cuk-vaf-svinka-pepa-hzpt.jpg",
			},
		"79" :  { 
			"category" : "Кондитерські вироби",
			"productCode" : "1518",
			"productFullName" : "Цукерки вафельні \"Ідея Фікс\" фл\/пак, екран 2,5 кг",
			"productName" : "Цук ваф Фиксики фл\/пак, экран 2,5 кг",
			"unit" : "кг.",
			"baseUnit" : "кг.",
			"coefficient" : "1",
			"previousPrice" : "0",
			"price" : "0",
			"minCountUnit" : "2.5",
			"promotion" : "1",
			"imgSrc" : "https:\/\/olegeduc.github.io\/food-trade\/image\/har'kov-hzpt\\cuk-vaf-fiksika-hzpt.jpg",
			},
		"80" :  { 
			"category" : "Кондитерські вироби",
			"productCode" : "4125",
			"productFullName" : "Цукерки вафельні \"Чарівна  історія\" фл\/пак, екран 1,5 кг",
			"productName" : "Цук ваф Чарівна  Історія фл\/пак, экран 1,5 кг",
			"unit" : "кг.",
			"baseUnit" : "кг.",
			"coefficient" : "1",
			"previousPrice" : "0",
			"price" : "0",
			"minCountUnit" : "1.5",
			"promotion" : "1",
			"imgSrc" : "https:\/\/olegeduc.github.io\/food-trade\/image\/har'kov-hzpt\\cuk-vaf-charivna-istorija-flpak-jekran-1-kg.jpg",
			},
		"81" :  { 
			"category" : "Кондитерські вироби",
			"productCode" : "3806",
			"productFullName" : "Цукерки Грильяж Фруктовий 1кг.",
			"productName" : "Цук Грильяж Фруктовий 1 кг.",
			"unit" : "кг.",
			"baseUnit" : "кг.",
			"coefficient" : "1",
			"previousPrice" : "0",
			"price" : "0",
			"minCountUnit" : "1",
			"promotion" : "1",
			"imgSrc" : "https:\/\/olegeduc.github.io\/food-trade\/image\/cuk-griljazh-fruktovij-1-kg.jpg",
			},
		"82" :  { 
			"category" : "Кондитерські вироби",
			"productCode" : "3613",
			"productFullName" : "Цукерки \"Дольче Де Коко\" глазур 1.7 кг.",
			"productName" : "Цук Дольче Де Коко глазур 1.7 кг. Гольскі",
			"unit" : "кг.",
			"baseUnit" : "кг.",
			"coefficient" : "1",
			"previousPrice" : "0",
			"price" : "0",
			"minCountUnit" : "1.7",
			"promotion" : "1",
			"imgSrc" : "https:\/\/olegeduc.github.io\/food-trade\/image\/gol'ski\\gol'ski-dolce-de-coco.jpg",
			},
		"83" :  { 
			"category" : "Кондитерські вироби",
			"productCode" : "3525",
			"productFullName" : "Цукерки \"Дольче Де Нат\" глазур 1.7 кг.ТМ \"Golski\"",
			"productName" : "Цук Дольче Де Нат глазур 1.7 кг. Гольскі",
			"unit" : "кг.",
			"baseUnit" : "кг.",
			"coefficient" : "1",
			"previousPrice" : "0",
			"price" : "0",
			"minCountUnit" : "1.7",
			"promotion" : "1",
			"imgSrc" : "https:\/\/olegeduc.github.io\/food-trade\/image\/gol'ski\\gol'ski-dolce-de-nut.jpg",
			},
		"84" :  { 
			"category" : "Кондитерські вироби",
			"productCode" : "3522",
			"productFullName" : "Цукерки \"Дольче Де Тірамісу\" глазур 1.7 кг.ТМ \"Golski\"",
			"productName" : "Цук Дольче Де Тірамісу глазур 1.7 кг. Гольскі",
			"unit" : "кг.",
			"baseUnit" : "кг.",
			"coefficient" : "1",
			"previousPrice" : "0",
			"price" : "0",
			"minCountUnit" : "1.7",
			"promotion" : "1",
			"imgSrc" : "https:\/\/olegeduc.github.io\/food-trade\/image\/gol'ski\\gol'ski-dolce-de-tiramisu.jpg",
			},
		"85" :  { 
			"category" : "Кондитерські вироби",
			"productCode" : "3564",
			"productFullName" : "Цукерки \"Dolce de Trufa\" глазур 1.7 кг. ТМ \"Golski\"",
			"productName" : "Цук Дольче де Труфа глазур 1.7 кг. Гольскі",
			"unit" : "кг.",
			"baseUnit" : "кг.",
			"coefficient" : "1",
			"previousPrice" : "0",
			"price" : "0",
			"minCountUnit" : "1.7",
			"promotion" : "1",
			"imgSrc" : "https:\/\/olegeduc.github.io\/food-trade\/image\/gol'ski\\cukerki-truffa-glazur-17-kggolski.jpg",
			},
		"86" :  { 
			"category" : "Кондитерські вироби",
			"productCode" : "3523",
			"productFullName" : "Цукерки \"Дольче Де Трюфель \" глазур 1.7 кг.ТМ \"Golski\"",
			"productName" : "Цук Дольче Де Трюфель глазур 1.7 кг. Гольскі",
			"unit" : "кг.",
			"baseUnit" : "кг.",
			"coefficient" : "1",
			"previousPrice" : "0",
			"price" : "0",
			"minCountUnit" : "1.7",
			"promotion" : "1",
			"imgSrc" : "https:\/\/olegeduc.github.io\/food-trade\/image\/gol'ski\\gol'ski-dolce-de-truffel.jpg",
			},
		"87" :  { 
			"category" : "Кондитерські вироби",
			"productCode" : "3519",
			"productFullName" : "Цукерки \"Кара-Кум\" глазур 2,2 кг.ТМ \"Golski\"",
			"productName" : "Цук Кара-Кум глазур 2,2 кг. Гольскі",
			"unit" : "кг.",
			"baseUnit" : "кг.",
			"coefficient" : "1",
			"previousPrice" : "0",
			"price" : "0",
			"minCountUnit" : "2.2",
			"promotion" : "1",
			"imgSrc" : "https:\/\/olegeduc.github.io\/food-trade\/image\/gol'ski\\gol'ski-kara-kum.jpg",
			},
		"88" :  { 
			"category" : "Кондитерські вироби",
			"productCode" : "3616",
			"productFullName" : "Цукерки \"NUTSI Batton\" не глазур 2,2 кг.ТМ \"Golski\"",
			"productName" : "Цук Натсі Баттон не глазур 2,2 кг. Гольскі",
			"unit" : "кг.",
			"baseUnit" : "кг.",
			"coefficient" : "1",
			"previousPrice" : "0",
			"price" : "0",
			"minCountUnit" : "2.2",
			"promotion" : "1",
			"imgSrc" : "https:\/\/olegeduc.github.io\/food-trade\/image\/gol'ski\\gol'ski-nutsi-batton.jpg",
			},
		"89" :  { 
			"category" : "Кондитерські вироби",
			"productCode" : "3970",
			"productFullName" : "Цукекри \"Рум'янок\" смак рому 2,2 кг.ТМ \"Golski\"",
			"productName" : "Цук Рум'янок смак рому 2,2 кг. Гольскі",
			"unit" : "кг.",
			"baseUnit" : "кг.",
			"coefficient" : "1",
			"previousPrice" : "0",
			"price" : "0",
			"minCountUnit" : "2.2",
			"promotion" : "1",
			"imgSrc" : "https:\/\/olegeduc.github.io\/food-trade\/image\/gol'ski\\gol'ski-rumjanok.jpg",
			},
		"90" :  { 
			"category" : "Кондитерські вироби",
			"productCode" : "4047",
			"productFullName" : "Цукерки \"Султан\" халва-арахіс глазур 2.2 кг.ТМ \"Golski\"",
			"productName" : "Цук Султан халва та арахіс глазур 2.2 кг. Гольскі",
			"unit" : "кг.",
			"baseUnit" : "кг.",
			"coefficient" : "1",
			"previousPrice" : "0",
			"price" : "0",
			"minCountUnit" : "2.2",
			"promotion" : "2",
			"imgSrc" : "https:\/\/olegeduc.github.io\/food-trade\/image\/gol'ski\\gol'ski-sultan.jpg",
			},
		"91" :  { 
			"category" : "Кондитерські вироби",
			"productCode" : "3844",
			"productFullName" : "Цукерки \"Україна - це ми\" глазур 1,5 кг ТМ \"Golski\"",
			"productName" : "Цук Україна - це ми глазур 1,5 кг Гольскі",
			"unit" : "кг.",
			"baseUnit" : "кг.",
			"coefficient" : "1",
			"previousPrice" : "0",
			"price" : "0",
			"minCountUnit" : "1.5",
			"promotion" : "2",
			"imgSrc" : "https:\/\/olegeduc.github.io\/food-trade\/image\/gol'ski\\cukerki-ukraina-ce-mi-glazur-15-kg-golski.jpg",
			},
		"92" :  { 
			"category" : "Кондитерські вироби",
			"productCode" : "3520",
			"productFullName" : "Цукерки \"Червоний мак\" глазур 2,2 кг. ТМ \"Golski\"",
			"productName" : "Цук Червоний мак глазур 2,2 кг. Гольскі",
			"unit" : "кг.",
			"baseUnit" : "кг.",
			"coefficient" : "1",
			"previousPrice" : "0",
			"price" : "0",
			"minCountUnit" : "2.2",
			"promotion" : "1",
			"imgSrc" : "https:\/\/olegeduc.github.io\/food-trade\/image\/gol'ski\\gol'ski-chervonij-mak.jpg",
			},
		"93" :  { 
			"category" : "Кондитерські вироби",
			"productCode" : "3623",
			"productFullName" : "Цукерки \"CHOKI Batton\" не глазур 2.2 кг.ТМ \"Golski\"",
			"productName" : "Цук Чокі Баттон не глазур 2.2 кг. Гольскі",
			"unit" : "кг.",
			"baseUnit" : "кг.",
			"coefficient" : "1",
			"previousPrice" : "0",
			"price" : "0",
			"minCountUnit" : "2.2",
			"promotion" : "1",
			"imgSrc" : "https:\/\/olegeduc.github.io\/food-trade\/image\/gol'ski\\gol'ski-choki-batton.jpg",
			},
		"94" :  { 
			"category" : "Кондитерські вироби",
			"productCode" : "2164",
			"productFullName" : "Шоколад Millennium Gold молочний з цілим горіхом 100г.",
			"productName" : "Шоколад Міленіум Голд молочний з цілим горіхом 100г.",
			"unit" : "шт.",
			"baseUnit" : "шт.",
			"coefficient" : "1",
			"previousPrice" : "0",
			"price" : "0",
			"minCountUnit" : "5",
			"promotion" : "1",
			"imgSrc" : "https:\/\/olegeduc.github.io\/food-trade\/image\/shokolad-mileniumgoldcillisgorih.jpg",
			},
		"95" :  { 
			"category" : "Кондитерські вироби",
			"productCode" : "2165",
			"productFullName" : "Шоколад Millennium Gold чорний з цілим горіхом 100г.",
			"productName" : "Шоколад Міленіум Голд чорний з цілим горіхом 100г.",
			"unit" : "шт.",
			"baseUnit" : "шт.",
			"coefficient" : "1",
			"previousPrice" : "0",
			"price" : "0",
			"minCountUnit" : "5",
			"promotion" : "1",
			"imgSrc" : "https:\/\/olegeduc.github.io\/food-trade\/image\/shokolad-chorn-mileniumgoldcillisgorih.jpg",
			},
		"96" :  { 
			"category" : "Кондитерські вироби",
			"productCode" : "4241",
			"productFullName" : "Шоколад \"ROSHEN\" пористий карамель 80 гр.",
			"productName" : "Шоколад Рошен пористий КАРАМЕЛЬ 80 гр.",
			"unit" : "шт.",
			"baseUnit" : "шт.",
			"coefficient" : "1",
			"previousPrice" : "0",
			"price" : "0",
			"minCountUnit" : "20",
			"promotion" : "1",
			"imgSrc" : "https:\/\/olegeduc.github.io\/food-trade\/image\/shokolad-roshen-poristij-karamel-80-gr.jpg",
			},
	},
}



export const productCategorys = {
	"Olija" : "Олія",
	"Konditers'ki-virobi" : "Кондитерські вироби",
 }

export const anouns = []